# A new Flutter project.
name: electroease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # FIXED: Using a standard, more flexible SDK range.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # FIXED: Adjusted to a common version compatible with the SDK.

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
