# A new Flutter project.
name: layout_masiqbal_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # FIXED: Using a standard, more flexible SDK range.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # FIXED: Adjusted to a common version compatible with the SDK.

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here.
  # FIXED: Added the required 'fonts:' key and corrected indentation.

  assets:
  - assets/images/ # FIXED: Menggunakan kunci 'assets:' dan path langsung
  - assets/images/gojek.png

  # ...
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf   # SEPERTI INI
        - asset: assets/fonts/Poppins-Bold.ttf    # SEPERTI INI
# ...